13:24:25.119 [MQTT Call: center] ERROR druid.sql.Statement - {conn-10010, stmt-20022} execute error. SELECT 1
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 1,455,390 milliseconds ago. The last packet sent successfully to the server was 1,455,405 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2363)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2481)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:302)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
	at com.alibaba.druid.wall.WallFilter.statement_executeQuery(WallFilter.java:510)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2481)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:302)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeQuery(StatementProxyImpl.java:211)
	at com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker.isValidConnection(MySqlValidConnectionChecker.java:128)
	at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1285)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1030)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:831)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
	at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2723)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:662)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:995)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:987)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:103)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy64.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
	at com.sun.proxy.$Proxy77.findByKey(Unknown Source)
	at com.ntu.center.sync.CenterDataReceiver.onReceive(CenterDataReceiver.java:57)
	at com.ntu.common.client.EMQTTClient$1.messageArrived(EMQTTClient.java:83)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:477)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:380)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:184)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 1,455,390 milliseconds ago. The last packet sent successfully to the server was 1,455,405 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:539)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:703)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:642)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:941)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:887)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1168)
	... 54 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:533)
	... 60 common frames omitted
13:24:44.248 [MQTT Call: center] ERROR druid.sql.Statement - {conn-10009, stmt-20023} execute error. SELECT 1
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 1,475,310 milliseconds ago. The last packet sent successfully to the server was 1,475,326 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2363)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2481)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:302)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
	at com.alibaba.druid.wall.WallFilter.statement_executeQuery(WallFilter.java:510)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2481)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:302)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeQuery(StatementProxyImpl.java:211)
	at com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker.isValidConnection(MySqlValidConnectionChecker.java:128)
	at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1285)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1030)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:831)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
	at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2723)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:662)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:995)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:987)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:103)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy64.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
	at com.sun.proxy.$Proxy77.findByKey(Unknown Source)
	at com.ntu.center.sync.CenterDataReceiver.onReceive(CenterDataReceiver.java:57)
	at com.ntu.common.client.EMQTTClient$1.messageArrived(EMQTTClient.java:83)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:477)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:380)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:184)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 1,475,310 milliseconds ago. The last packet sent successfully to the server was 1,475,326 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:539)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:703)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:642)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:941)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:887)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1168)
	... 54 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:533)
	... 60 common frames omitted
13:24:44.474 [MQTT Call: center] ERROR com.ntu.common.client.EMQTTClient - 客户机未连接
org.eclipse.paho.client.mqttv3.MqttException: 客户机未连接
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:177)
	at org.eclipse.paho.client.mqttv3.MqttTopic.publish(MqttTopic.java:116)
	at com.ntu.common.client.EMQTTClient.publish(EMQTTClient.java:123)
	at com.ntu.center.sync.CenterDataReceiver.onReceive(CenterDataReceiver.java:188)
	at com.ntu.common.client.EMQTTClient$1.messageArrived(EMQTTClient.java:83)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:477)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:380)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:184)
	at java.lang.Thread.run(Thread.java:748)
13:24:44.492 [MQTT Rec: center] ERROR com.ntu.common.client.EMQTTClient - -----------连接断开-----------
13:51:22.726 [Timer-0] ERROR org.eclipse.paho.client.mqttv3.internal.ClientState - center: Timed out as no write activity, keepAlive=30,000 lastOutboundActivity=1,590,040,222,724 lastInboundActivity=1,590,040,211,698 time=1,590,040,282,725 lastPing=1,590,040,192,724
13:52:50.663 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 451 号数据同步失败原因: 中央数据库中已存在此条数据
13:53:01.674 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 440 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:36.728 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 206 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:37.731 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 207 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:38.732 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 208 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:39.735 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 209 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:40.739 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 210 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:41.747 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 211 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:42.733 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 212 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:43.738 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 213 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:44.735 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 214 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:45.738 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 215 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:46.737 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 216 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:47.739 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 217 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:48.738 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 218 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:49.745 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 219 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:50.740 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 220 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:51.746 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 221 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:52.785 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 222 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:53.744 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 223 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:54.744 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 224 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:55.757 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 225 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:56.746 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 226 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:57.747 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 227 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:58.751 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 228 号数据同步失败原因: 中央数据库中已存在此条数据
13:54:59.748 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 229 号数据同步失败原因: 中央数据库中已存在此条数据
13:55:00.756 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 230 号数据同步失败原因: 中央数据库中已存在此条数据
13:55:01.751 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 231 号数据同步失败原因: 中央数据库中已存在此条数据
13:55:02.750 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 232 号数据同步失败原因: 中央数据库中已存在此条数据
13:55:03.754 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 233 号数据同步失败原因: 中央数据库中已存在此条数据
13:55:04.759 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 234 号数据同步失败原因: 中央数据库中已存在此条数据
13:55:05.754 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 235 号数据同步失败原因: 中央数据库中已存在此条数据
13:55:06.757 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 236 号数据同步失败原因: 中央数据库中已存在此条数据
14:18:32.609 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - tjh_node 节点的 BOX_SENSOR 表中的 451 号数据同步失败原因: 中央数据库中已存在此条数据
17:10:09.912 [MQTT Call: center] ERROR com.ntu.common.client.EMQTTClient - 客户机未连接
org.eclipse.paho.client.mqttv3.MqttException: 客户机未连接
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:177)
	at org.eclipse.paho.client.mqttv3.MqttTopic.publish(MqttTopic.java:116)
	at com.ntu.common.client.EMQTTClient.publish(EMQTTClient.java:123)
	at com.ntu.center.sync.CenterDataReceiver.onReceive(CenterDataReceiver.java:188)
	at com.ntu.common.client.EMQTTClient$1.messageArrived(EMQTTClient.java:83)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:477)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:380)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:184)
	at java.lang.Thread.run(Thread.java:748)
17:10:09.920 [MQTT Rec: center] ERROR com.ntu.common.client.EMQTTClient - -----------连接断开-----------
17:10:26.006 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 279 号数据同步失败原因:  中央数据库没有此条数据
17:21:02.374 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 279 号数据同步失败原因:  中央数据库没有此条数据
17:40:43.220 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 455 号数据同步失败原因: 
17:40:43.221 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30165ms.
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve com.ntu.center.mapper.DataSyncMapper.findByKey
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30165ms.
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30165ms.
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve com.ntu.center.mapper.DataSyncMapper.findByKey
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30165ms.
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy64.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
	at com.sun.proxy.$Proxy77.findByKey(Unknown Source)
	at com.ntu.center.sync.CenterDataReceiver.onReceive(CenterDataReceiver.java:57)
	at com.ntu.common.client.EMQTTClient$1.messageArrived(EMQTTClient.java:83)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:477)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:380)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:184)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30165ms.
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve com.ntu.center.mapper.DataSyncMapper.findByKey
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30165ms.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 11 common frames omitted
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30165ms.
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 17 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30165ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:689)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	... 27 common frames omitted
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2490)
	at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:556)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:169)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185)
	... 32 common frames omitted
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:1171)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:576)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2486)
	... 35 common frames omitted
17:40:43.222 [MQTT Call: center] ERROR com.ntu.common.client.EMQTTClient - 客户机未连接
org.eclipse.paho.client.mqttv3.MqttException: 客户机未连接
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:177)
	at org.eclipse.paho.client.mqttv3.MqttTopic.publish(MqttTopic.java:116)
	at com.ntu.common.client.EMQTTClient.publish(EMQTTClient.java:123)
	at com.ntu.center.sync.CenterDataReceiver.onReceive(CenterDataReceiver.java:188)
	at com.ntu.common.client.EMQTTClient$1.messageArrived(EMQTTClient.java:83)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:477)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:380)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:184)
	at java.lang.Thread.run(Thread.java:748)
17:40:48.322 [MQTT Rec: center] ERROR com.ntu.common.client.EMQTTClient - -----------连接断开-----------
17:40:59.402 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 463 号数据同步失败原因: 中央数据库中已存在此条数据
17:43:35.998 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'Processor5': Unsatisfied dependency expressed through field 'areaSpotMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'areaSpotMapper' defined in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\com\ntu\center\mapper\AreaSpotMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.cj.jdbc.Driver
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.ntu.center.CenterClientApplication.main(CenterClientApplication.java:14)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'areaSpotMapper' defined in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\com\ntu\center\mapper\AreaSpotMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.cj.jdbc.Driver
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1526)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1290)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1210)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 19 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.cj.jdbc.Driver
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1290)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1210)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1511)
	... 30 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.cj.jdbc.Driver
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1290)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1210)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 43 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.cj.jdbc.Driver
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 57 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot load driver class: com.mysql.cj.jdbc.Driver
	at org.springframework.util.Assert.state(Assert.java:94)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:222)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.initializeDataSourceBuilder(DataSourceProperties.java:174)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration.createDataSource(DataSourceConfiguration.java:43)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari.dataSource(DataSourceConfiguration.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 58 common frames omitted
17:54:17.374 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 475 号数据同步失败原因: 中央数据库中已存在此条数据
18:46:42.745 [Timer-0] ERROR org.eclipse.paho.client.mqttv3.internal.ClientState - center: Timed out as no write activity, keepAlive=30,000 lastOutboundActivity=1,590,057,942,613 lastInboundActivity=1,590,057,942,066 time=1,590,058,002,614 lastPing=1,590,057,918,807
20:34:05.443 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 361 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:06.445 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 362 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:07.445 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 363 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:08.458 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 364 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:09.460 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 365 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:10.446 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 366 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:11.450 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 367 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:12.445 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 368 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:13.489 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 369 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:14.455 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 370 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:15.450 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 371 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:16.453 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 372 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:17.452 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 373 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:18.455 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 374 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:19.453 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 375 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:20.459 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 376 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:21.456 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 377 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:22.457 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 378 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:23.458 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 379 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:24.459 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 380 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:25.460 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 381 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:26.460 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 382 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:27.449 [pool-2-thread-5] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 384 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:27.462 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 383 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:29.758 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 385 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:30.537 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 386 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:31.499 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 387 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:32.477 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 388 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:33.462 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 389 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:34.456 [pool-2-thread-5] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 391 号数据同步失败原因: 中央数据库中已存在此条数据
20:34:34.471 [pool-2-thread-4] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 MONITOR_DATA 表中的 390 号数据同步失败原因: 中央数据库中已存在此条数据
20:37:54.602 [pool-2-thread-7] ERROR com.ntu.center.sync.CenterDataReceiver - tjh_node 节点的 BOX_SENSOR 表中的 463 号数据同步失败原因: 中央数据库中已存在此条数据
